//go:build !ignore_autogenerated

// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArcaContentSource) DeepCopyInto(out *ArcaContentSource) {
	*out = *in
	if in.SourceVolumeID != nil {
		in, out := &in.SourceVolumeID, &out.SourceVolumeID
		*out = new(string)
		**out = **in
	}
	if in.SourceSnapshotID != nil {
		in, out := &in.SourceSnapshotID, &out.SourceSnapshotID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArcaContentSource.
func (in *ArcaContentSource) DeepCopy() *ArcaContentSource {
	if in == nil {
		return nil
	}
	out := new(ArcaContentSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArcaSnapshot) DeepCopyInto(out *ArcaSnapshot) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArcaSnapshot.
func (in *ArcaSnapshot) DeepCopy() *ArcaSnapshot {
	if in == nil {
		return nil
	}
	out := new(ArcaSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArcaSnapshot) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArcaSnapshotList) DeepCopyInto(out *ArcaSnapshotList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ArcaSnapshot, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArcaSnapshotList.
func (in *ArcaSnapshotList) DeepCopy() *ArcaSnapshotList {
	if in == nil {
		return nil
	}
	out := new(ArcaSnapshotList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArcaSnapshotList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArcaSnapshotSpec) DeepCopyInto(out *ArcaSnapshotSpec) {
	*out = *in
	in.CreatedAt.DeepCopyInto(&out.CreatedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArcaSnapshotSpec.
func (in *ArcaSnapshotSpec) DeepCopy() *ArcaSnapshotSpec {
	if in == nil {
		return nil
	}
	out := new(ArcaSnapshotSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArcaSnapshotStatus) DeepCopyInto(out *ArcaSnapshotStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArcaSnapshotStatus.
func (in *ArcaSnapshotStatus) DeepCopy() *ArcaSnapshotStatus {
	if in == nil {
		return nil
	}
	out := new(ArcaSnapshotStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArcaVolume) DeepCopyInto(out *ArcaVolume) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArcaVolume.
func (in *ArcaVolume) DeepCopy() *ArcaVolume {
	if in == nil {
		return nil
	}
	out := new(ArcaVolume)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArcaVolume) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArcaVolumeList) DeepCopyInto(out *ArcaVolumeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ArcaVolume, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArcaVolumeList.
func (in *ArcaVolumeList) DeepCopy() *ArcaVolumeList {
	if in == nil {
		return nil
	}
	out := new(ArcaVolumeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArcaVolumeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArcaVolumeSpec) DeepCopyInto(out *ArcaVolumeSpec) {
	*out = *in
	in.CreatedAt.DeepCopyInto(&out.CreatedAt)
	if in.ContentSource != nil {
		in, out := &in.ContentSource, &out.ContentSource
		*out = new(ArcaContentSource)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArcaVolumeSpec.
func (in *ArcaVolumeSpec) DeepCopy() *ArcaVolumeSpec {
	if in == nil {
		return nil
	}
	out := new(ArcaVolumeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArcaVolumeStatus) DeepCopyInto(out *ArcaVolumeStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArcaVolumeStatus.
func (in *ArcaVolumeStatus) DeepCopy() *ArcaVolumeStatus {
	if in == nil {
		return nil
	}
	out := new(ArcaVolumeStatus)
	in.DeepCopyInto(out)
	return out
}
