name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

permissions:
  contents: read

jobs:
  python-tests:
    uses: ./.github/workflows/python-tests.yml

  openstack-python-tests:
    uses: ./.github/workflows/openstack-python-tests.yml

  ansible-lint:
    uses: ./.github/workflows/ansible-lint.yml

  csi-tests:
    uses: ./.github/workflows/csi-tests.yml

  deb-build:
    uses: ./.github/workflows/deb-build.yml

  rpm-build:
    uses: ./.github/workflows/rpm-build.yml
